[tool.poetry]
name = "benchmarks"
version = "0.1.0"
description = ""
authors = ["suhavni <suhavni@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
locust = "^2.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
